CREATE TABLE IF NOT EXISTS individuals (
    individual_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mrn VARCHAR(128) UNIQUE,
    external_identifier VARCHAR(128) UNIQUE
);

CREATE TABLE IF NOT EXISTS sample_accessions (
    sample_accession_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accession_identifier VARCHAR(128) NOT NULL UNIQUE,
    individual_id BIGINT NOT NULL,
    dna_source VARCHAR(128),
    CONSTRAINT fk_sample_accessions_individual
        FOREIGN KEY (individual_id) REFERENCES individuals(individual_id)
);

CREATE TABLE IF NOT EXISTS lab_protocols (
    lab_protocol_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technology VARCHAR(128) NOT NULL,
    manufacturer VARCHAR(128),
    miscellaneous VARCHAR(512),
    CONSTRAINT uq_lab_protocol UNIQUE (technology, manufacturer)
);

CREATE TABLE IF NOT EXISTS sample_tests (
    sample_test_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_accession_id BIGINT NOT NULL,
    lab_protocol_id BIGINT NOT NULL,
    test_type VARCHAR(64) NOT NULL,
    CONSTRAINT fk_sample_tests_accession
        FOREIGN KEY (sample_accession_id) REFERENCES sample_accessions(sample_accession_id),
    CONSTRAINT fk_sample_tests_protocol
        FOREIGN KEY (lab_protocol_id) REFERENCES lab_protocols(lab_protocol_id)
);

CREATE TABLE IF NOT EXISTS pipelines (
    pipeline_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_name VARCHAR(128) NOT NULL,
    software_version VARCHAR(64),
    settings_used VARCHAR(1024),
    CONSTRAINT uq_pipeline UNIQUE (software_name, software_version)
);

CREATE TABLE IF NOT EXISTS source_files (
    source_file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(1000),
    pipeline_id BIGINT NOT NULL,
    imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    import_status VARCHAR(50) NOT NULL,
    row_count INTEGER NOT NULL,
    notes VARCHAR(1000),
    CONSTRAINT fk_source_files_pipeline
        FOREIGN KEY (pipeline_id) REFERENCES pipelines(pipeline_id)
);

CREATE TABLE IF NOT EXISTS sample_test_results (
    sample_test_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_test_id BIGINT NOT NULL,
    pipeline_id BIGINT NOT NULL,
    source_file_id BIGINT,
    genome_build VARCHAR(64) NOT NULL,
    calling_method VARCHAR(128),
    raw_iscn VARCHAR(4096),
    annotation_names VARCHAR(8192),
    line_number INTEGER,
    CONSTRAINT fk_results_test
        FOREIGN KEY (sample_test_id) REFERENCES sample_tests(sample_test_id),
    CONSTRAINT fk_results_pipeline
        FOREIGN KEY (pipeline_id) REFERENCES pipelines(pipeline_id),
    CONSTRAINT fk_results_source_file
        FOREIGN KEY (source_file_id) REFERENCES source_files(source_file_id)
);

CREATE TABLE IF NOT EXISTS karyotypes (
    karyotype_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_test_result_id BIGINT NOT NULL,
    karyotype_text VARCHAR(4096) NOT NULL,
    clone_number INTEGER,
    cell_count INTEGER,
    abnormalities VARCHAR(4096),
    CONSTRAINT fk_karyotypes_result
        FOREIGN KEY (sample_test_result_id) REFERENCES sample_test_results(sample_test_result_id)
);

CREATE TABLE IF NOT EXISTS genomic_segments (
    segment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_test_result_id BIGINT NOT NULL,
    karyotype_id BIGINT,
    chromosome VARCHAR(32) NOT NULL,
    start_pos BIGINT NOT NULL,
    stop_pos BIGINT NOT NULL,
    cytoband_start VARCHAR(64),
    cytoband_end VARCHAR(64),
    event_type VARCHAR(64) NOT NULL,
    copy_number INTEGER NOT NULL,
    array_score DOUBLE PRECISION,
    confidence VARCHAR(64),
    number_of_sites INTEGER,
    annotations VARCHAR(8192),
    CONSTRAINT fk_segments_result
        FOREIGN KEY (sample_test_result_id) REFERENCES sample_test_results(sample_test_result_id),
    CONSTRAINT fk_segments_karyotype
        FOREIGN KEY (karyotype_id) REFERENCES karyotypes(karyotype_id),
    CONSTRAINT ck_segment_interval CHECK (start_pos <= stop_pos)
);

CREATE INDEX IF NOT EXISTS idx_segments_region
    ON genomic_segments(chromosome, start_pos, stop_pos);

CREATE TABLE IF NOT EXISTS validation_issues (
    validation_issue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segment_id BIGINT,
    source_file_id BIGINT,
    line_number INTEGER,
    sample_accession_id VARCHAR(128),
    issue_type VARCHAR(128) NOT NULL,
    issue_message VARCHAR(2048) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    CONSTRAINT fk_validation_segment
        FOREIGN KEY (segment_id) REFERENCES genomic_segments(segment_id),
    CONSTRAINT fk_validation_source_file
        FOREIGN KEY (source_file_id) REFERENCES source_files(source_file_id)
);
