CREATE TABLE IF NOT EXISTS individuals (
    individual_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mrn VARCHAR(128) UNIQUE,
    external_identifier VARCHAR(128) UNIQUE
);

CREATE TABLE IF NOT EXISTS sample_accessions (
    sample_accession_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accession_identifier VARCHAR(128) NOT NULL UNIQUE,
    individual_id BIGINT NOT NULL,
    dna_source VARCHAR(128),
    CONSTRAINT fk_sample_accessions_individual
        FOREIGN KEY (individual_id) REFERENCES individuals(individual_id)
);

CREATE TABLE IF NOT EXISTS lab_protocols (
    lab_protocol_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technology VARCHAR(128) NOT NULL,
    manufacturer VARCHAR(128),
    miscellaneous VARCHAR(512),
    CONSTRAINT uq_lab_protocol UNIQUE (technology, manufacturer)
);

CREATE TABLE IF NOT EXISTS sample_tests (
    sample_test_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_accession_id BIGINT NOT NULL,
    lab_protocol_id BIGINT NOT NULL,
    test_type VARCHAR(64) NOT NULL,
    CONSTRAINT fk_sample_tests_accession
        FOREIGN KEY (sample_accession_id) REFERENCES sample_accessions(sample_accession_id),
    CONSTRAINT fk_sample_tests_protocol
        FOREIGN KEY (lab_protocol_id) REFERENCES lab_protocols(lab_protocol_id)
);

CREATE TABLE IF NOT EXISTS pipelines (
    pipeline_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_name VARCHAR(128) NOT NULL,
    software_version VARCHAR(64),
    settings_used VARCHAR(1024),
    CONSTRAINT uq_pipeline UNIQUE (software_name, software_version)
);

CREATE TABLE IF NOT EXISTS source_files (
    source_file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(1000),
    pipeline_id BIGINT NOT NULL,
    imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    import_status VARCHAR(50) NOT NULL,
    row_count INTEGER NOT NULL,
    notes VARCHAR(1000),
    CONSTRAINT fk_source_files_pipeline
        FOREIGN KEY (pipeline_id) REFERENCES pipelines(pipeline_id)
);

CREATE TABLE IF NOT EXISTS sample_test_results (
    sample_test_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_test_id BIGINT NOT NULL,
    pipeline_id BIGINT NOT NULL,
    source_file_id BIGINT,
    genome_build VARCHAR(64) NOT NULL,
    calling_method VARCHAR(128),
    raw_iscn VARCHAR(4096),
    annotation_names VARCHAR(8192),
    line_number INTEGER,
    CONSTRAINT fk_results_test
        FOREIGN KEY (sample_test_id) REFERENCES sample_tests(sample_test_id),
    CONSTRAINT fk_results_pipeline
        FOREIGN KEY (pipeline_id) REFERENCES pipelines(pipeline_id),
    CONSTRAINT fk_results_source_file
        FOREIGN KEY (source_file_id) REFERENCES source_files(source_file_id)
);

CREATE TABLE IF NOT EXISTS karyotypes (
    karyotype_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_test_result_id BIGINT NOT NULL,
    karyotype_text VARCHAR(4096) NOT NULL,
    clone_number INTEGER,
    cell_count INTEGER,
    abnormalities VARCHAR(4096),
    CONSTRAINT fk_karyotypes_result
        FOREIGN KEY (sample_test_result_id) REFERENCES sample_test_results(sample_test_result_id)
);

CREATE TABLE IF NOT EXISTS genomic_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_test_result_id BIGINT NOT NULL,
    source_file_id BIGINT,
    event_group_id VARCHAR(128),
    event_type VARCHAR(64) NOT NULL,
    genome_build VARCHAR(64) NOT NULL,
    calling_method VARCHAR(128),
    raw_event_text VARCHAR(4096),
    line_number INTEGER,
    event_status VARCHAR(64) NOT NULL DEFAULT 'IMPORTED',
    confidence VARCHAR(64),
    annotations VARCHAR(8192),
    CONSTRAINT fk_events_result
        FOREIGN KEY (sample_test_result_id) REFERENCES sample_test_results(sample_test_result_id),
    CONSTRAINT fk_events_source_file
        FOREIGN KEY (source_file_id) REFERENCES source_files(source_file_id)
);

CREATE TABLE IF NOT EXISTS genomic_segments (
    segment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT,
    sample_test_result_id BIGINT NOT NULL,
    karyotype_id BIGINT,
    chromosome VARCHAR(32) NOT NULL,
    start_pos BIGINT NOT NULL,
    stop_pos BIGINT NOT NULL,
    cytoband_start VARCHAR(64),
    cytoband_end VARCHAR(64),
    event_type VARCHAR(64) NOT NULL,
    copy_number INTEGER NOT NULL,
    array_score DOUBLE PRECISION,
    confidence VARCHAR(64),
    number_of_sites INTEGER,
    annotations VARCHAR(8192),
    CONSTRAINT fk_segments_event
        FOREIGN KEY (event_id) REFERENCES genomic_events(event_id),
    CONSTRAINT fk_segments_result
        FOREIGN KEY (sample_test_result_id) REFERENCES sample_test_results(sample_test_result_id),
    CONSTRAINT fk_segments_karyotype
        FOREIGN KEY (karyotype_id) REFERENCES karyotypes(karyotype_id),
    CONSTRAINT ck_segment_interval CHECK (start_pos <= stop_pos)
);

CREATE INDEX IF NOT EXISTS idx_segments_region
    ON genomic_segments(chromosome, start_pos, stop_pos);

CREATE INDEX IF NOT EXISTS idx_segments_event
    ON genomic_segments(event_id);

CREATE TABLE IF NOT EXISTS genomic_links (
    link_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    source_segment_id BIGINT NOT NULL,
    target_segment_id BIGINT NOT NULL,
    link_type VARCHAR(64) NOT NULL,
    orientation VARCHAR(64),
    evidence VARCHAR(1024),
    confidence VARCHAR(64),
    CONSTRAINT fk_links_event
        FOREIGN KEY (event_id) REFERENCES genomic_events(event_id),
    CONSTRAINT fk_links_source_segment
        FOREIGN KEY (source_segment_id) REFERENCES genomic_segments(segment_id),
    CONSTRAINT fk_links_target_segment
        FOREIGN KEY (target_segment_id) REFERENCES genomic_segments(segment_id)
);

CREATE INDEX IF NOT EXISTS idx_links_event
    ON genomic_links(event_id);

CREATE TABLE IF NOT EXISTS validation_issues (
    validation_issue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segment_id BIGINT,
    source_file_id BIGINT,
    line_number INTEGER,
    sample_accession_id VARCHAR(128),
    issue_type VARCHAR(128) NOT NULL,
    issue_message VARCHAR(2048) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    CONSTRAINT fk_validation_segment
        FOREIGN KEY (segment_id) REFERENCES genomic_segments(segment_id),
    CONSTRAINT fk_validation_source_file
        FOREIGN KEY (source_file_id) REFERENCES source_files(source_file_id)
);

CREATE TABLE IF NOT EXISTS variant_classifications (
    classification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segment_id BIGINT NOT NULL,
    classification_label VARCHAR(64) NOT NULL,
    guideline_system VARCHAR(128),
    guideline_version VARCHAR(64),
    evidence_score DOUBLE PRECISION,
    evidence_summary VARCHAR(4096),
    classified_by VARCHAR(128),
    classified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    review_status VARCHAR(64) NOT NULL,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    supersedes_classification_id BIGINT,
    CONSTRAINT fk_classifications_segment
        FOREIGN KEY (segment_id) REFERENCES genomic_segments(segment_id),
    CONSTRAINT fk_classifications_supersedes
        FOREIGN KEY (supersedes_classification_id) REFERENCES variant_classifications(classification_id),
    CONSTRAINT ck_classification_label CHECK (
        classification_label IN ('Pathogenic', 'Likely Pathogenic', 'VUS', 'Likely Benign', 'Benign')
    ),
    CONSTRAINT ck_classification_review_status CHECK (
        review_status IN ('Draft', 'In review', 'Needs more evidence', 'Ready for sign-out', 'Signed out', 'Superseded')
    )
);

CREATE INDEX IF NOT EXISTS idx_classifications_segment
    ON variant_classifications(segment_id, is_current);

CREATE TABLE IF NOT EXISTS signed_out_calls (
    signed_out_call_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segment_id BIGINT NOT NULL,
    classification_id BIGINT NOT NULL,
    individual_id BIGINT NOT NULL,
    sample_test_result_id BIGINT NOT NULL,
    clinical_significance VARCHAR(128) NOT NULL,
    relevance_to_indication VARCHAR(512),
    interpretation_text VARCHAR(4096),
    signed_out_status VARCHAR(64) NOT NULL,
    signed_out_by VARCHAR(128),
    signed_out_at TIMESTAMP,
    report_text VARCHAR(4096),
    report_version VARCHAR(64),
    amended_from_signed_out_call_id BIGINT,
    CONSTRAINT fk_signed_out_segment
        FOREIGN KEY (segment_id) REFERENCES genomic_segments(segment_id),
    CONSTRAINT fk_signed_out_classification
        FOREIGN KEY (classification_id) REFERENCES variant_classifications(classification_id),
    CONSTRAINT fk_signed_out_individual
        FOREIGN KEY (individual_id) REFERENCES individuals(individual_id),
    CONSTRAINT fk_signed_out_result
        FOREIGN KEY (sample_test_result_id) REFERENCES sample_test_results(sample_test_result_id),
    CONSTRAINT fk_signed_out_amended_from
        FOREIGN KEY (amended_from_signed_out_call_id) REFERENCES signed_out_calls(signed_out_call_id),
    CONSTRAINT ck_signed_out_clinical_significance CHECK (
        clinical_significance IN ('Diagnostic', 'Carrier', 'Incidental', 'Unclear relevance', 'Not clinically relevant')
    ),
    CONSTRAINT ck_signed_out_status CHECK (
        signed_out_status IN ('Not started', 'In review', 'Signed out', 'Amended', 'Retracted')
    )
);

CREATE INDEX IF NOT EXISTS idx_signed_out_segment
    ON signed_out_calls(segment_id, individual_id);

CREATE INDEX IF NOT EXISTS idx_signed_out_classification
    ON signed_out_calls(classification_id);

CREATE INDEX IF NOT EXISTS idx_signed_out_result_status
    ON signed_out_calls(sample_test_result_id, signed_out_status);

CREATE TABLE IF NOT EXISTS notes (
    note_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_table VARCHAR(128) NOT NULL,
    target_id BIGINT NOT NULL,
    note_type VARCHAR(64) NOT NULL,
    note_text VARCHAR(4096) NOT NULL,
    author VARCHAR(128),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_notes_target_table CHECK (
        target_table IN ('genomic_segments', 'variant_classifications', 'signed_out_calls')
    ),
    CONSTRAINT ck_notes_note_type CHECK (
        note_type IN ('Reviewer note', 'Evidence note', 'Sign-out note', 'Import note', 'Follow-up note')
    )
);

CREATE INDEX IF NOT EXISTS idx_notes_target
    ON notes(target_table, target_id);
